### ISSUE TITLE
Statsderl application crashing when being called with high frequency

### ISSUE THREAD

**Issue by szarsti** [lpgauth/statsderl#20]
I am experiencing errors on production system under high load (which means statsderl is called very frequently). Those errors are crashing statsderl application, which in turn causes to whole erlang interpreter termination.

I get in logs:

    16:43:50.808 [error] CRASH REPORT Process statsderl_1 with 0 neighbours crashed with reason: no function clause matching statsderl_server:handle_msg({inet_reply,#Port<0.170403>,{error,eperm}}, {state,<<31,189,149,202,194,181,112,114,111,100,117,99,116,105,111,110,46,100,100,98,45,109,101,...>>,...}) line 46
    16:43:50.808 [error] Supervisor statsderl_sup had child undefined started with statsderl_server:start_link(statsderl_1) at <0.4125.5> exit with reason function_clause in context child_terminated
    16:43:50.991 [error] CRASH REPORT Process statsderl_1 with 0 neighbours crashed with reason: no function clause matching statsderl_server:handle_msg({inet_reply,#Port<0.177218>,{error,eperm}}, {state,<<31,189,149,202,194,181,112,114,111,100,117,99,116,105,111,110,46,100,100,98,45,109,101,...>>,...}) line 46
    16:43:50.992 [error] Supervisor statsderl_sup had child undefined started with statsderl_server:start_link(statsderl_1) at <0.10894.5> exit with reason function_clause in context child_terminated
    16:43:50.992 [error] Supervisor statsderl_sup had child undefined started with statsderl_server:start_link(statsderl_1) at <0.10894.5> exit with reason reached_max_restart_intensity in context shutdown
    16:43:50.992 [info] Application statsderl exited with reason: shutdown
    16:43:50.992 [error] gen_server <0.193.0> terminated with reason: unexpected_delivery_and_no_default_consumer
    16:43:50.993 [error] gen_server <0.207.0> terminated with reason: unexpected_delivery_and_no_default_consumer
    16:43:50.993 [error] CRASH REPORT Process <0.207.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1145
    16:43:50.993 [error] CRASH REPORT Process <0.193.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1145
    {"Kernel pid terminated",application_controller,"{application_terminated,statsderl,shutdown}"}

It happens only when system is under high load. Under smaller load everything works just fine. Als changing rate parameter in statsderl calls does not seem to make any difference.

I am running most resent statsderl v0.4.3.

**Comment by lpgauth** [comment]
Hi @szarsti,
It looks like a permission issue on your UDP socket `{error,eperm}`. I'll add a case so it doesn't crash StatsDerl, but I'm not sure what to do when it does. I could log an error, but if it's called too fast it will crash the VM (OOM).

**Comment by lpgauth** [comment]
Fixed in 0.4.4.
