### ISSUE TITLE
Suggestion: Allow start params

### ISSUE THREAD

**Issue by xmppjingle** [lpgauth/statsderl#32]
For cases where no Environments variables are set, or usage of other config tools like confetti. Would be nice to have possibility to start the application passing parameters, instead of having them being read hardcoded in ENV vars.

If this turns to be a case, I'd be glad to add the possibility without breaking backward compatibility

**Comment by lpgauth** [comment]
Environment variables are the defacto way to configure Erlang applications. They aren't hard coded, you can change them while loading the application.

e.g.
```erlang
application:load(statsderl).
application:set_env(statsderl, port, 9999).
application:ensure_all_started(statsderl).
```
