### ISSUE TITLE
Implement meters and historgrams

### ISSUE THREAD

**Issue by shezarkhani** [lpgauth/statsderl#44]
According to the StatsD spec (the only one available...) histograms and meters are part of the protocol, but statsderl currently does not support these metrics:

https://github.com/b/statsd_spec
https://github.com/etsy/statsd/wiki/Protocol

Other clients that do support these metrics:

Codahale StatsD reporter:  https://github.com/organicveggie/metrics-statsd/blob/master/src/main/java/com/bealetech/metrics/reporting/StatsdReporter.java#L129
Go: https://github.com/alexcesaro/statsd/blob/master/statsd.go

**Comment by shezarkhani** [comment]
I'd like to point out that histograms are much like "timers" but an alias on the statsderl API is needed. meters are also like counters but can only increment.

**Comment by lpgauth** [comment]
@shezarkhani these should be trivial to add, but before I do can you tell me wich servers support these? Since there's no official specs I've noticed there's a lot of "protocol forks".

**Comment by shezarkhani** [comment]
you're right. I can't find many servers that actually do implement these.
